# Generated by Django 5.2.17 on 2026-09-22 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
